app:
  datasource:
    commerce:
      url: jdbc:mysql://localhost:3306/commerce?autoReconnect=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: commerce
      password: commerce
      driver-class-name: com.mysql.cj.jdbc.Driver # Fully qualified name of the JDBC driver. Auto-detected based on the URL by default.
# Loading class `com.mysql.jdbc.Driver'. This is deprecated.
# The new driver class is `com.mysql.cj.jdbc.Driver'.
# The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

    inventory:
      url: jdbc:mysql://localhost:3306/inventory?autoReconnect=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: inventory
      password: inventory
      driver-class-name: com.mysql.cj.jdbc.Driver # Fully qualified name of the JDBC driver. Auto-detected based on the URL by default.

spring:
  application:
    name: multidbdemo
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    database: MYSQL
#    show_sql: true
#    generate-ddl: true # Whether to initialize the schema on startup.
#    hibernate: #this property is not being read
#      ddl-auto: create-drop # DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Defaults to "create-drop" when using an embedded database and no schema manager was detected. Otherwise, defaults to "none".
#      format_sql: true # To beautify or pretty print the SQL
server:
  port: 9005
  servlet:
    context-path: /multidbdemo
